title: "DevOps/SRE FastTrack — Курс до Middle"
description: "Самодостаточный учебник с практикой"
theme: jekyll-theme-cayman

markdown: kramdown
kramdown:
  input: GFM
permalink: pretty

plugins:
  - jekyll-seo-tag

collections:
  modules:
    output: true
   
    permalink: /modules/:name/

defaults:
  - scope:
      path: ""
      type: "modules"
    values:
      layout: page
